### ISSUE TITLE
Windows executable error

### ISSUE THREAD

**Issue by red-erik** [jhuckaby/performa-satellite#3]
Hello,
on Windows 10 I receive

(node:24564) UnhandledPromiseRejectionWarning: Error: not supported
    at process.nextTick (C:\snapshot\node_modules\performa-satellite\node_modules\systeminformation\lib\filesystem.js:502:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:24564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24564) UnhandledPromiseRejectionWarning: Error: not supported
    at process.nextTick (C:\snapshot\node_modules\performa-satellite\node_modules\systeminformation\lib\filesystem.js:356:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:24564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Regards,
Red.

**Comment by jhuckaby** [comment]
Thanks for the issue report -- I figured that wouldn't work.  I don't have a Windows machine to develop or test on, so that Windows EXE is just provided "as is" in case it happens to work.  I suspect the NPM [systeminformation](https://www.npmjs.com/package/systeminformation) package isn't fully compatible with Windows 10, which I am relying on to collect metrics in the satellite.

**Comment by red-erik** [comment]
Hello,
the 4.0 of NPM systeminformation says:
"supports Linux, macOS, **partial Windows**, FreeBSD, OpenBSD, NetBSD and SunOS support"
Let's wait a full support release ;-)

Red.

**Comment by kenrmayfield** [comment]
@jhuckaby 

Is it possible that you can Compile 32Bit Windows File for performa-satellite-win.exe?

**Comment by jhuckaby** [comment]
@kenrmayfield Alas, pkg doesn't support it: https://www.npmjs.com/package/pkg#targets

**Comment by kenrmayfield** [comment]
@jhuckaby 

Is there any other way to make performa-satellite Agent to work with a Windows 32Bit OS?

**Comment by jhuckaby** [comment]
@kenrmayfield I have no idea, sorry.  If you can get Node.js installed somehow, then you can try downloading the entire GitHub repo and just running it manually.

https://github.com/jhuckaby/performa-satellite/archive/refs/heads/master.zip

```sh
node index.js
```

**Comment by kenrmayfield** [comment]
@jhuckaby 

Can you Compile a 32Bit Version of the performa-satellite Agent?

**Users requiring Node.js on a 32-bit Windows system should use an older version, such as those in the v22.x LTS line (supported until April 2027) or v20.x LTS line (supported until April 2026).** To download these older versions, users can visit the Node.js website and navigate to the "Previous Releases" section.

https://nodejs.org/download/release/

**Comment by jhuckaby** [comment]
This is out of my control.  I use a 3rd party library called [pkg](https://www.npmjs.com/package/pkg) which does this for me.  I just configure it to run.  I have it selected on Node.js v18:

https://github.com/jhuckaby/performa-satellite/blob/master/package.json#L24

**Comment by kenrmayfield** [comment]
@jhuckaby 

Since you are using pkg and Configure for Node.JS v18 then why is their no Windows 32Bit EXE Compiled?

Node.JS up too Version 22.x Supports 32Bit.

**Comment by jhuckaby** [comment]
I have no idea, sorry.
